--- #YAML:1.0
name:               Dpchrist-CGI
version:            1.062
abstract:           utility subroutines for CGI scripts
author:
    - David Paul Christensen <dpchrist@holgerdanske.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Capture::Tiny:        0.06
    Carp:                 1.08
    CGI:                  3.29
    Data::Dumper:         2.12114
    Digest::MD5:          2.3601
    Dpchrist::Debug:      1.049
    Dpchrist::Is:         1.031
    Dpchrist::LangUtil:   1.018
    Exporter:             5.62
    ExtUtils::MakeMaker:  6.54
    File::Basename:       2.76
    Test::Compile:        0.1
    Test::Manifest:       1.22
    Test::More:           0.72
    Test::Pod:            1.4
    Test::Prereq:         1.037
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
